name: Push results of react build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - frontend/build/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install js
        run: npm ci
        working-directory: ./frontend

      - name: Run js tests
        run: npm run tests --if-present
        working-directory: ./frontend

      - name: Build static web site
        run: npm run build:development
        working-directory: ./frontend

      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: 'Your commit message'
          add: 'frontend/build/'
