name: Push results of react build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - frontend/build/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: wow-actions/use-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install js
        run: npm ci
        working-directory: ./frontend

      - name: Run js tests
        run: npm run tests --if-present
        working-directory: ./frontend

      - name: Build static web site
        run: npm run build:development
        working-directory: ./frontend

      - name: allow build folder to be added to repository
        run: sed -i '/build/d' frontend/.gitignore

      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: 'Automatic react build'
          add: 'frontend/build/'
