on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  package:

    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.8'

    steps:
    - name: Checkout the project
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ env.PYTHON }}
        cache: 'pip'

    - name: Install Requirements
      run: pip install -r backend/requirements.txt

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build the library
      run: pip install .

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}