name: Python CI

on:
  push:
    branches: [ pydevelopment ]
  pull_request:
    branches: [ main ]
    paths:
      - backend/**

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'

    steps:
    - name: Checkout the project
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
        cache: 'pip'

    - name: Install Requirements
      run: pip install -r backend/requirements.txt

    - name: Generate Report
      run:  coverage run -m unittest
    
