name: Python CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9

    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m unittest
    
